name: 'gedankenfolger/faq'
typeName: gedankenfolger_faq
group: default
prefixFields: true
prefixType: full
fields:
  - identifier: TYPO3/Header
    type: Basic
  - identifier: header_link
    useExistingField: true
  - identifier: tabRecords
    type: Tab
  - identifier: storageFolder
    type: Select
    renderType: selectMultipleSideBySide
    foreign_table: 'pages'
    foreign_table_where: 'AND {#pages}.{#doktype}=254 ORDER BY pages.sorting'
    size: 5
    maxitems: 1
  - identifier: recursive
    type: Number
    format: integer
    default: 0
    range:
      lower: 0
      upper: 10
  - identifier: orderBy
    type: Text
    placeholder: 'sorting'
    searchable: false
  - identifier: tabFilter
    type: Tab
  - identifier: filterByCategory
    type: Select
    renderType: selectMultipleSideBySide
    foreign_table: 'sys_category'
    foreign_table_where: 'ORDER BY sys_category.sorting'
    size: 5
    maxitems: 5
  - identifier: tabSettings
    type: Tab
  - identifier: paletteOpenOnLoad
    type: Palette
    fields:
      - identifier: openItem
        type: Select
        renderType: selectSingle
        items:
          - label: '-'
            value: ''
          - value: first
          - value: uid
        onChange: reload
      - type: Linebreak
      - identifier: openByUid
        type: Select
        renderType: selectMultipleSideBySide
        foreign_table: 'tx_gedankenfolger_faq_item'
        foreign_table_where: 'ORDER BY pages.sorting'
        size: 1
        maxitems: 1
        displayCond: 'FIELD:openItem:=:uid'
  - identifier: openSingleOnly
    type: Checkbox
  - identifier: groupByCategory
    type: Checkbox
    onChange: reload
  - identifier: showCategoryTitles
    type: Checkbox
    displayCond: 'FIELD:groupByCategory:=:1'

