name: 'gedankenfolger/faq-item'
table: tx_gedankenfolger_faq_item
prefixFields: false
labelField: question
fields:
  - identifier: question
    type: Text
    required: true
  - identifier: answer
    type: Textarea
    enableRichtext: true
  - identifier: categories
    type: Tab
  - identifier: categories
    type: Category
    allowed: 'sys_category'
    relationship: manyToMany
  - identifier: settings
    type: Tab
  - identifier: colorVariant
    type: Select
    renderType: selectSingle
    items:
      - value: standard
        label: 'Standard'
      - value: primary
        label: 'Primary'
      - value: secondary
        label: 'Secondary'
      - value: tertiary
        label: 'Tertiary'
