name: 'gedankenfolger/faq-item'
table: tx_gedankenfolger_faq_item
prefixFields: false
labelField: question
fields:
  - identifier: question
    type: Text
    required: true
  - identifier: answer
    type: Textarea
    enableRichtext: true
  - identifier: categories
    type: Tab
  - identifier: categories
    type: Category
    allowed: 'sys_category'
    relationship: manyToMany
  - identifier: settings
    type: Tab
  - identifier: colorVariant
    type: Select
    renderType: selectSingle
    default: 'default'
    items:
      - value: default
      - value: primary
      - value: secondary
      - value: tertiary
